### PR TITLE
Challenges

### PR DESCRIPTION
**Pull request by Mika587**
Thank you so much for your patience, Pava! I literally feel like a lost kid in a candy shop and you seem to speak magic and understand exactly where I am. Let's see if I managed to do it properly this time.

### CODE REVIEW

**Comment by iampava** [comment]
Yes! This is it! Add me as a contributor in this project so I can "approve" this pull request. As I mentioned in the training, other team members would look over your code and give feedback (if needed).

To add me as a contributor, go into **Settings**:
image

 and then **Manage Access** subpage:

image

**Comment by Mika587** [comment]
Thank you, Păvă. I added you as a contributor yesterday. Can you check, please, and let me know if I didn't do it correctly? I'm not close to a laptop atm but as soon as I can I'll have a look too.

**Comment by iampava** [comment]
Oh, you're right. Totally missed that! Will merge now 😉

**Comment by iampava** [comment]
It seems you've completed all steps, hooray!

You can move on to steps 29-33 and create a PR in our repo. If you run into any trouble, let me know. You can create an issue into our repo and talk there: https://github.com/FrontEnd-ro/git-github-practice-exercises/issues/new

**Pull request merged**
